### GENERAL
baseURL: https://serhii.vasylenko.info
languageCode: en-us

theme: "PaperMod"

### BUILD
buildDrafts: false
buildFuture: false
buildExpired: false
publishDir: publishdir
minify:
    disableXML: true
    minifyOutput: true

### SEO
enableRobotsTXT: true
title: Serhii Vasylenko
googleAnalytics: G-GK7SE0XWGK

### NAVIGATION
permalinks:
  posts: :year/:month/:day/:slug

menu:
    main:
        - identifier: about
          name: "About me"
          url: /about/
          weight: 2
        - identifier: tags
          name: "Tags"
          url: /tags/
          weight: 1
        - identifier: cv
          name: "My CV"
          url: /cv/
          weight: 3

### DECORATIONS
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: monokai


### THEME SETTINGS
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Serhii Vasylenko â€” Personal Blog
    description: "Personal blog of Serhii Vasylenko â€” aws community builder, devops, developer experience engineer at Grammarly"
    keywords: [Blog, DevOps, AWS, Terraform, Ukraine, Tutorials, Education]
    author: Serhii Vasylenko
    images: ["/assets/img/website-logo-open-graph.jpeg"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false
    ShowFullTextinRSS: true
    ShowReadingTime: false
    ShowShareButtons: true
    ShareButtons: ["twitter", "linkedin", "facebook", "reddit"]
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    schema:
        publisherType: "Person"

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/favicon.ico"
        favicon16x16: "/favicon-16x16.png"
        favicon32x32: "/favicon-32x32.png"
        apple_touch_icon: "/apple-touch-icon.png"
        safari_pinned_tab: "/safari-pinned-tab.svg"

    label:
        text: "Home"
        icon: "/apple-touch-icon.png"

    homeInfoParams:
        Title: "Hi! ðŸ‘‹ I am Serhii Vasylenko and this is my blog"
        Content: "Here I write about my DevOps experience, technologies, tutorials and some day-to-day work as a Developer Experience engineer at Grammarly."

    socialIcons:
        - name: twitter
          url: "https://twitter.com/vasylenko"
        - name: dev
          url: "https://dev.to/svasylenko"
        - name: linkedin
          url: "https://stackoverflow.com"
        - name: github
          url: "https://github.com/vasylenko"
        - name: "facebook"
          url: "https://www.facebook.com/vasylenkos"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page
        responsiveImages: true

    editPost:
        URL: "mailto:serhii@vasylenko.info"
        Text: "Suggest Changes" # edit text
        appendFilePath: false # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]