baseURL: https://devdosvid.blog
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepComments: false
      keepSpecialComments: true
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: false
      keepWhitespace: false

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
